import React, { createContext, useContext, ReactNode } from "react";
import { I18nManager } from "react-native";

interface LanguageContextType {
  isRTL: boolean;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<string, string> = {
  appName: "Bezoar",
  dashboard: "داشبورد",
  patients: "بیماران",
  drugs: "داروها",
  sales: "فروش",
  reports: "گزارشات",
  backup: "پشتیبان‌گیری",
  settings: "تنظیمات",
  addPatient: "افزودن بیمار",
  editPatient: "ویرایش بیمار",
  addDrug: "افزودن دارو",
  editDrug: "ویرایش دارو",
  newSale: "فروش جدید",
  editSale: "ویرایش فروش",
  totalPatients: "کل بیماران",
  bottlesSold: "بطری فروخته شده",
  unitsSold: "فروخته شده",
  totalSales: "کل فروش",
  debtBalance: "مانده بدهی",
  patientsWithDebt: "بیماران بدهکار",
  monthlySales: "فروش ماهانه",
  recentPatients: "بیماران اخیر",
  recentSales: "فروش اخیر",
  noPatients: "هیچ بیماری یافت نشد",
  noDrugs: "هیچ دارویی یافت نشد",
  noSales: "هیچ فروشی یافت نشد",
  noData: "داده‌ای یافت نشد",
  save: "ذخیره",
  cancel: "لغو",
  delete: "حذف",
  edit: "ویرایش",
  search: "جستجو",
  searchPatients: "جستجوی بیماران...",
  searchDrugs: "جستجوی داروها...",
  searchSales: "جستجوی فروش...",
  filter: "فیلتر",
  all: "همه",
  paid: "پرداخت شده",
  unpaid: "پرداخت نشده",
  partial: "پرداخت جزئی",
  installment: "قسطی",
  firstName: "نام",
  lastName: "نام خانوادگی",
  fullName: "نام کامل",
  nationalId: "کد ملی",
  phone: "تلفن",
  address: "آدرس",
  dateOfBirth: "تاریخ تولد",
  gender: "جنسیت",
  male: "مرد",
  female: "زن",
  other: "سایر",
  mainDisease: "بیماری اصلی",
  backgroundDiseases: "بیماری‌های زمینه‌ای",
  medicalDescription: "شرح پزشکی",
  treatmentPlan: "برنامه درمان",
  treatmentDuration: "مدت درمان",
  doctorNotes: "یادداشت‌های پزشک",
  identityInformation: "اطلاعات هویتی",
  medicalInformation: "اطلاعات پزشکی",
  drugName: "نام دارو",
  drugCode: "کد دارو",
  drugType: "نوع دارو",
  purchasePrice: "قیمت خرید",
  salePrice: "قیمت فروش",
  unit: "واحد",
  bottle: "بطری",
  box: "جعبه",
  pack: "بسته",
  selectPatient: "انتخاب بیمار",
  selectDrug: "انتخاب دارو",
  bottleCount: "تعداد بطری",
  quantity: "تعداد",
  pricePerBottle: "قیمت هر بطری",
  pricePerUnit: "قیمت واحد",
  totalPrice: "قیمت کل",
  totalAmount: "مبلغ کل",
  paidAmount: "مبلغ پرداخت شده",
  remainingAmount: "مبلغ باقی‌مانده",
  paymentStatus: "وضعیت پرداخت",
  purchaseDate: "تاریخ خرید",
  saleDate: "تاریخ فروش",
  notes: "یادداشت‌ها",
  installments: "اقساط",
  addInstallment: "افزودن قسط",
  amount: "مبلغ",
  dueDate: "تاریخ سررسید",
  paymentDate: "تاریخ پرداخت",
  status: "وضعیت",
  createBackup: "ایجاد پشتیبان",
  restoreBackup: "بازیابی پشتیبان",
  exportToFile: "خروجی به فایل",
  importFromFile: "ورودی از فایل",
  copyToClipboard: "کپی در کلیپ‌بورد",
  restoreFromClipboard: "بازیابی از کلیپ‌بورد",
  backupCreated: "پشتیبان ایجاد شد",
  backupRestored: "پشتیبان بازیابی شد",
  exportAllData: "خروجی تمام داده‌ها به صورت JSON",
  importFromBackup: "ورود داده از فایل پشتیبان",
  resetDatabase: "بازنشانی پایگاه داده",
  deleteAllDataPermanently: "حذف دائمی تمام داده‌ها",
  backupInfo: "پشتیبان‌ها شامل تمام بیماران، داروها، فروش‌ها و سوابق اقساط است. داده‌های پشتیبان را در مکان امنی ذخیره کنید.",
  theme: "پوسته",
  darkMode: "حالت تاریک",
  lightMode: "حالت روشن",
  error: "خطا",
  success: "موفق",
  warning: "هشدار",
  confirm: "تأیید",
  updatePatient: "بروزرسانی بیمار",
  updateDrug: "بروزرسانی دارو",
  updateSale: "بروزرسانی فروش",
  loading: "در حال بارگذاری...",
  noResults: "نتیجه‌ای یافت نشد",
  required: "الزامی",
  invalid: "نامعتبر",
  bottles: "بطری",
  toman: "تومان",
  rial: "ریال",
  monthly: "ماهانه",
  weekly: "هفتگی",
  daily: "روزانه",
  viewAll: "مشاهده همه",
  statistics: "آمار",
  salesChart: "نمودار فروش",
  noChartData: "داده‌ای برای نمایش وجود ندارد",
  appearance: "ظاهر",
  general: "عمومی",
  about: "درباره",
  version: "نسخه",
  madeWithLove: "ساخته شد با عشق برای سیروس و اشرفی",
  dataManagement: "مدیریت داده",
  clearAllData: "پاک کردن همه داده‌ها",
  areYouSure: "آیا مطمئن هستید؟",
  thisCannotBeUndone: "این عمل قابل بازگشت نیست",
  confirmDelete: "تأیید حذف",
  deleteConfirmMessage: "این کار تمام بیماران، داروها، فروش‌ها و سوابق پرداخت را به طور دائمی حذف می‌کند.",
  allDataDeleted: "همه داده‌ها حذف شد",
  backupCopied: "پشتیبان در کلیپ‌بورد کپی شد",
  clipboardEmpty: "کلیپ‌بورد خالی است",
  invalidBackupFormat: "فرمت فایل پشتیبان نامعتبر است",
  invalidBackupData: "داده پشتیبان در کلیپ‌بورد نامعتبر است",
  foundData: "یافت شد",
  restoreQuestion: "بازیابی شود؟",
  sharingNotAvailable: "اشتراک‌گذاری در این دستگاه امکان‌پذیر نیست",
  fileDownloaded: "فایل دانلود شد",
  failedToCreateBackup: "خطا در ایجاد پشتیبان",
  failedToExport: "خطا در خروجی گرفتن به فایل",
  patientDrugManagement: "مدیریت بیمار و دارو",
  appDescription: "برنامه مدیریت بیماران و داروها برای پیگیری فروش و پرداخت‌ها. طراحی شده برای استفاده آفلاین با ذخیره‌سازی محلی داده.",
  selectGender: "انتخاب جنسیت",
  enterFirstName: "نام را وارد کنید",
  enterLastName: "نام خانوادگی را وارد کنید",
  enterNationalId: "کد ملی را وارد کنید",
  enterPhone: "شماره تلفن را وارد کنید",
  enterAddress: "آدرس را وارد کنید",
  enterMainDisease: "بیماری اصلی را وارد کنید",
  enterBackgroundDiseases: "بیماری‌های زمینه‌ای را وارد کنید",
  enterMedicalDescription: "شرح پزشکی را وارد کنید",
  enterTreatmentPlan: "برنامه درمان را وارد کنید",
  enterTreatmentDuration: "مدت درمان را وارد کنید",
  enterDoctorNotes: "یادداشت‌های پزشک را وارد کنید",
  enterDrugName: "نام دارو را وارد کنید",
  enterDrugCode: "کد دارو را وارد کنید",
  enterDrugType: "نوع دارو را وارد کنید",
  enterPurchasePrice: "قیمت خرید را وارد کنید",
  enterSalePrice: "قیمت فروش را وارد کنید",
  enterQuantity: "تعداد را وارد کنید",
  enterNotes: "یادداشت را وارد کنید",
  patientSaved: "بیمار ذخیره شد",
  patientUpdated: "بیمار بروزرسانی شد",
  patientDeleted: "بیمار حذف شد",
  drugSaved: "دارو ذخیره شد",
  drugUpdated: "دارو بروزرسانی شد",
  drugDeleted: "دارو حذف شد",
  saleSaved: "فروش ذخیره شد",
  saleUpdated: "فروش بروزرسانی شد",
  saleDeleted: "فروش حذف شد",
  installmentSaved: "قسط ذخیره شد",
  installmentDeleted: "قسط حذف شد",
  markAsPaid: "علامت‌گذاری به عنوان پرداخت شده",
  patientDetails: "جزئیات بیمار",
  drugDetails: "جزئیات دارو",
  saleDetails: "جزئیات فروش",
  salesHistory: "سابقه فروش",
  paymentHistory: "سابقه پرداخت",
  noSalesHistory: "سابقه فروشی وجود ندارد",
  noPaymentHistory: "سابقه پرداختی وجود ندارد",
  today: "امروز",
  yesterday: "دیروز",
  thisWeek: "این هفته",
  thisMonth: "این ماه",
  thisYear: "امسال",
  custom: "سفارشی",
  from: "از",
  to: "تا",
  apply: "اعمال",
  reset: "بازنشانی",
  profit: "سود",
  revenue: "درآمد",
  expense: "هزینه",
  inventory: "موجودی",
  lowStock: "کمبود موجودی",
  outOfStock: "اتمام موجودی",
  inStock: "موجود",
  stock: "موجودی",
  addStock: "افزودن موجودی",
  removeStock: "کاهش موجودی",
  smartRestoreInfo: "فقط داده‌های جدید اضافه می‌شود و موارد تکراری نادیده گرفته می‌شوند.",
  noNewDataToRestore: "همه داده‌ها از قبل موجود است. موردی اضافه نشد.",
  newPatient: "بیمار جدید",
  newDrug: "دارو جدید",
  newSale: "فروش جدید",
  newInstallment: "قسط جدید",
  dataRestored: "داده‌ها بازیابی شد",
};

if (!I18nManager.isRTL) {
  I18nManager.forceRTL(true);
  I18nManager.allowRTL(true);
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const t = (key: string): string => {
    return translations[key] || key;
  };

  return (
    <LanguageContext.Provider
      value={{
        isRTL: true,
        t,
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
